#pragma config(Motor,  port2,           arm,           tmotorNormal, openLoop)
#pragma config(Motor,  port3,           arm1,          tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main ()
{
  motor[arm]= 70;

  motor[arm1]= 70;
wait1Msec(3000);

motor[arm]= -70;
motor[arm1]= -70;
wait1Msec(3000);
}
