#pragma config(Motor,  port2,           conv1,         tmotorNormal, openLoop)
#pragma config(Motor,  port3,           conv2,         tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main ()
{

  while(1 == 1)
  {
    motor[conv1]  = (vexRT[Ch2]);
    motor[conv2] = (vexRT[Ch2]);


  }
}

