#pragma config(Motor,  port2,           RightFront,    tmotorVex393, openLoop)
#pragma config(Motor,  port3,           RightBack,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           LeftFront,     tmotorVex393, openLoop)
#pragma config(Motor,  port5,           LeftBack,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           LiftLeftTop,   tmotorVex393, openLoop)
#pragma config(Motor,  port7,           LiftLeftBottom, tmotorVex393, openLoop)
#pragma config(Motor,  port8,           LiftRightTop,  tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           LiftRightBottom, tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void set(string type,int magnitude){
  if (type=="lift"){
        motor[LiftLeftBottom] = magnitude;
        motor[LiftLeftTop] = magnitude;
        motor[LiftRightBottom] = magnitude;   //pushing forward on the left joystick goes forward
        motor[LiftRightTop] = magnitude;      //pushing side to side on the right joystick turns
      }                                       //6 controls the lift
  if (type=="right"){                         //rotissarator is 5
       motor[RightBack] = magnitude;
       motor[RightFront] = magnitude;
    }
  if (type=="left"){
       motor[LeftBack] = magnitude;
       motor[LeftFront] = magnitude;
    }
}
task main()
{
  while(true)
  {
     if(vexRT[Btn6U]==1)
     {
        set("lift",127);
     }
     else if(vexRT[Btn6D]==1)
     {
        set("lift",-127);
     }
     else
     {
       set("lift",0);
     }

     if(abs(vexRT[Ch2]) > 50)
     {
       set("right", vexRT[Ch2]);
       set("left",vexRT[Ch2]);
     }
     else
     {
       set("right",0);
       set("left",0);
     }

      if(abs(vexRT[Ch4]) > 50)
     {
       set("left",vexRT[Ch4]);
       set("right",-vexRT[Ch4]);
     }
     else
     {
       set("left",0);
       set("right",0);
     }
  }
}
