#pragma config(Motor,  port2,           lift1,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           lift2,         tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main
{
  while(true)
  {
    if(vexRT[Btn6U] == 1)
    {
      motor[lift1] = 127;
      motor[lift2] = 127;
    }
    else
    {
      if(vexRT[Btn6D] == 1)
      {
        motor[lift1] = -127;
        motor[lift2] = -127;
      }
      else
      {
        motor[lift1] = 0;
        motor[lift2] = 0;
      }
    }
  }
}
