#pragma config(Sensor, dgtl1,  ,                    sensorSONAR_inch)
#pragma config(Motor,  port2,           ,              tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while (0==0)
{

   motor[port2]=SensorValue[dgtl1];


}


}
