#pragma config(Sensor, dgtl1,  sonar,               sensorSONAR_inch)
#pragma config(Motor,  port2,           side1,         tmotorNormal, openLoop)
#pragma config(Motor,  port3,           front1,        tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port4,           side2,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port5,           front2,        tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
    motor[front1]=40;
    motor[front2]=40;
    motor[side1]=0;
    motor[side2]=0;

    wait1Msec(1000);

    motor[front1]=0;
    motor[front2]=0;
    motor[side1]=40;
    motor[side2]=40;

    wait1Msec(1000);

    motor[front1]=-40;
    motor[front2]=-40;
    motor[side1]=0;
    motor[side2]=0;

    wait1Msec(1000);

    motor[front1]=0;
    motor[front2]=0;
    motor[side1]=-40;
    motor[side2]=-40;

    wait1Msec(1000);

    motor[front1]=-40;
    motor[front2]=40;
    motor[side1]=40;
    motor[side2]=-40;

    wait1Msec(2000);

    motor[front1]=-40;
    motor[front2]=-40;
    motor[side1]=40;
    motor[side2]=40;

    wait1Msec(2000);

    }
