#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           FL,            tmotorVex393, openLoop)
#pragma config(Motor,  port3,           FR,            tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           BR,            tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port5,           BL,            tmotorVex393, openLoop, encoder, encoderPort, I2C_2, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int leftencoder;
int rightencoder;

task main()
{

	while(true){

		leftencoder = nMotorEncoder[BL];
		rightencoder = nMotorEncoder[BR];
}

}
