#pragma config(Sensor, dgtl1,  pid1enc,        sensorQuadEncoder)
#pragma config(Motor,  port2,           pid1,          tmotorVex393, PIDControl, encoder, encoderPort, dgtl1, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
		motor[pid1] = 80;
	}
}
