#pragma config(Sensor, in1,    pot,            sensorPotentiometer)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int potValue;
task main()
{
	while(true){
		potValue = SensorValue[pot];
	}
}
