#pragma config(Sensor, in1,    armPot,         sensorPotentiometer)
#pragma config(Sensor, in2,    accelX,         sensorAnalog)
#pragma config(Sensor, in3,    accelY,         sensorAnalog)
#pragma config(Sensor, in4,    accelZ,         sensorAnalog)
#pragma config(Sensor, in5,    gyro,           sensorGyro)
#pragma config(Sensor, in6,    pwrExp,         sensorAnalog)
#pragma config(Sensor, in7,    autoPosition,   sensorPotentiometer)
#pragma config(Sensor, in8,    autoPlan,       sensorPotentiometer)
#pragma config(Sensor, dgtl1,  encoderR,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encoderL,       sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  touchBase,      sensorTouch)
#pragma config(Sensor, dgtl6,  touchTop,       sensorTouch)
#pragma config(Sensor, dgtl7,  jumperSkills,   sensorTouch)
#pragma config(Sensor, dgtl11, pPunchL,        sensorDigitalOut)
#pragma config(Sensor, dgtl12, pPunchR,        sensorDigitalOut)
#pragma config(Motor,  port1,           intakeL,       tmotorVex393, openLoop)
#pragma config(Motor,  port2,           RD,            tmotorVex393, openLoop)
#pragma config(Motor,  port3,           armRU,         tmotorVex393, openLoop)
#pragma config(Motor,  port4,           armRD,         tmotorVex393, openLoop)
#pragma config(Motor,  port5,           RU,            tmotorVex393, openLoop)
#pragma config(Motor,  port6,           LU,            tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           armLD,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           armLU,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           LD,            tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          intakeR,       tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "Drive.c"
#include "Auto.c"


/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	StartTask(background);
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	skillsAutonomous();
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop
	while(true){
		chasTank(Ch3, Ch2, 20, 110, 2);
		armContinuous(Btn6U, Btn6D);
		armBasePreset(Btn8D);
		armBumpPreset(Btn8L);
		armBarPreset(Btn8R);
		armTopPreset(Btn8U);
		intkMovePunch(Btn7R);
		intkPunch(Btn7D);
		intake(Btn5U, Btn5D);
		chasLCD();
	}
}
