#pragma config(Sensor, in1,    armPot,         sensorPotentiometer)
#pragma config(Sensor, in2,    accelX,         sensorAnalog)
#pragma config(Sensor, in3,    accelY,         sensorAnalog)
#pragma config(Sensor, in4,    accelZ,         sensorAnalog)
#pragma config(Sensor, in5,    gyro,           sensorGyro)
#pragma config(Sensor, in6,    pwrExp,         sensorAnalog)
#pragma config(Sensor, in7,    autoPosition,   sensorPotentiometer)
#pragma config(Sensor, in8,    autoPlan,       sensorPotentiometer)
#pragma config(Sensor, dgtl1,  encoderR,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encoderL,       sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  touchBase,      sensorTouch)
#pragma config(Sensor, dgtl6,  touchTop,       sensorTouch)
#pragma config(Sensor, dgtl7,  jumperSkills,   sensorTouch)
#pragma config(Sensor, dgtl11, pPunchL,        sensorDigitalOut)
#pragma config(Sensor, dgtl12, pPunchR,        sensorDigitalOut)
#pragma config(Motor,  port1,           armLD,         tmotorVex393, openLoop)
#pragma config(Motor,  port2,           RD,            tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           LD,            tmotorVex393, openLoop)
#pragma config(Motor,  port4,           RU,            tmotorVex393, openLoop)
#pragma config(Motor,  port5,           LU,            tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           armRU,         tmotorVex393, openLoop)
#pragma config(Motor,  port7,           armLU,         tmotorVex393, openLoop)
#pragma config(Motor,  port8,           intakeL,       tmotorVex393, openLoop)
#pragma config(Motor,  port9,           intakeR,       tmotorVex393, openLoop)
#pragma config(Motor,  port10,          armRD,         tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Motor,  port1,           intakeL,       tmotorVex393, openLoop)
////#pragma config(Motor,  port2,           RD,            tmotorVex393, openLoop)
//#pragma config(Motor,  port3,           armRU,         tmotorVex393, openLoop)
//#pragma config(Motor,  port4,           armRD,         tmotorVex393, openLoop)
////#pragma config(Motor,  port5,           RU,            tmotorVex393, openLoop)
////#pragma config(Motor,  port6,           LU,            tmotorVex393, openLoop, reversed)
//#pragma config(Motor,  port7,           armLD,         tmotorVex393, openLoop, reversed)
//#pragma config(Motor,  port8,           armLU,         tmotorVex393, openLoop, reversed)
////#pragma config(Motor,  port9,           LD,            tmotorVex393, openLoop, reversed)
//#pragma config(Motor,  port10,          intakeR,       tmotorVex393, openLoop, reversed)
////*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Drive.c"
#include "Auto.c"

task main()
{
	StartTask(background);
	while(true){
		setChas(127, 127);
	}
}
