#pragma config(Sensor, in1,    armPotentiometer,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  encoderR,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encoderL,       sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  touchBottom,    sensorTouch)
#pragma config(Sensor, dgtl6,  touchTop,       sensorTouch)
#pragma config(Sensor, dgtl7,  touchAuto,      sensorTouch)
#pragma config(Sensor, dgtl8,  autoSelect,     sensorTouch)
#pragma config(Sensor, dgtl11, pIntakeU,       sensorDigitalOut)
#pragma config(Sensor, dgtl12, pIntakeD,       sensorDigitalOut)
#pragma config(Motor,  port1,           intakeL,       tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port2,           RU,            tmotorVex393, openLoop)
#pragma config(Motor,  port3,           armRU,         tmotorVex393, openLoop)
#pragma config(Motor,  port4,           RD,            tmotorVex393, openLoop)
#pragma config(Motor,  port5,           armRD,         tmotorVex393, openLoop)
#pragma config(Motor,  port6,           armLD,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           LD,            tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           armLU,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           LU,            tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          intakeR,       tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/*Debugging checklist
	-do autonomous functions work?
	-remove activation part of channel updating?
	-isolate where it is
		*sending values to ROBOT
		*getting values from controller
		*functions that update powers from channel values
		*other?
*/
#include "C:\Documents and Settings\Robot\Desktop\StormTroopers\Code 2013-14\Code 2.0\DriverControl.c"
#include "C:\Documents and Settings\Robot\Desktop\StormTroopers\Code 2013-14\Code 2.0\BackgroundTasks.c"
#include "C:\Documents and Settings\Robot\Desktop\StormTroopers\Code 2013-14\Code 2.0\AutoControl.c"
//Nathan approves,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
void driverMaster(){
	chasTank(Ch3Xmtr2, Ch2Xmtr2, 20, 105, 2);

	armUp(Btn6U);
	armDown(Btn6D);

	intake(Btn5UXmtr2, Btn5DXmtr2);
}

void driverNathan(){
	chasArcade(Ch3, Ch4, 20, 105, 2);

	intake(Btn5U, Btn5D);

	armUp(Btn6U);
	armDown(Btn6D);

	armTopPreset(Btn8U);
	armBarPreset(Btn8R);
	armBumpPreset(Btn8L);
	armBasePreset(Btn8D);
}

void driverJoseph(){
	chasTank(Ch3, Ch2, 20, 105, 2);

	armBasePreset(Btn8D);
	armTopPreset(Btn8U);
	armBumpPreset(Btn8L);
	armBarPreset(Btn8R);
	armUp(Btn6U);
	armDown(Btn6D);

	intake(Btn5U, Btn5D);
}

task main()
{
	initializeAdam();
	adam.pidSpeedLeft.activated = false;
	adam.pidSpeedRight.activated = false;
	activateMain();
	activateAlt();
	int masterButton = Btn8DXmtr2;
	StartTask(background);
	wait1Msec(250);
	/*while(true){
		if(adam.channels[masterButton][CH_CURRENT] == 1 && adam.channels[masterButton][CH_OLD] == 0){
			driverMaster();
		}else{
			driverJoseph();
		}
	}*/
	armRaise();
	move(127, 300);
}
