#pragma config(Sensor, in1,    potent1,        sensorPotentiometer)
#pragma config(Sensor, in6,    lineLeft,       sensorLineFollower)
#pragma config(Sensor, in7,    lineMiddle,     sensorLineFollower)
#pragma config(Sensor, in8,    lineRight,      sensorLineFollower)
#pragma config(Sensor, dgtl1,  touch,          sensorTouch)
#pragma config(Sensor, dgtl2,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl4,  encoderRight,   sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  encoderLeft,    sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  beltTouch,      sensorTouch)
#pragma config(Sensor, dgtl9,  encoderArm,     sensorQuadEncoder)
#pragma config(Sensor, dgtl11, team,           sensorTouch)
#pragma config(Sensor, dgtl12, jumper,         sensorTouch)
#pragma config(Motor,  port1,           beltRight2,    tmotorNormal, openLoop)
#pragma config(Motor,  port2,           frontLeft,     tmotorNormal, openLoop)
#pragma config(Motor,  port3,           frontRight,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port4,           backRight,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port5,           backLeft,      tmotorNormal, openLoop)
#pragma config(Motor,  port6,           liftRight,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port7,           liftLeft,      tmotorNormal, openLoop)
#pragma config(Motor,  port8,           beltRight,     tmotorNormal, openLoop)
#pragma config(Motor,  port9,           beltLeft,      tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port10,          beltLeft2,     tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#pragma platform(VEX)

void Right(int AmountGiven)
{
  int AmountCalculated;
  if (AmountGiven>-127)
  {
    AmountCalculated=-127;
  }
  if (AmountGiven>-100)
  {
    AmountCalculated=-50;
  }
  if (AmountGiven>0)
  {
    AmountCalculated=50;
  }
  if (AmountGiven>100)
  {
    AmountCalculated=127;
  }
  motor[frontRight] = AmountCalculated;
  motor[backRight] = AmountCalculated;
}
void Left(int AmountGiven)
{
  int AmountCalculated;
  if (AmountGiven>-127)
  {
    AmountCalculated=-127;
  }
  if (AmountGiven>-100)
  {
    AmountCalculated=-50;
  }
  if (AmountGiven>0)
  {
    AmountCalculated=50;
  }
  if (AmountGiven>100)
  {
    AmountCalculated=127;
  }
  motor[frontLeft] = AmountCalculated;
  motor[backLeft] = AmountCalculated;
}
task main()
{
  while(true)
  {
  if (abs(vexRT[Ch2])>50)
    {
      if (motor[frontLeft]==0)
        {
        Right(vexRT[Ch2]);
        }
    }
  if (abs(vexRT[Ch3])>50)
    {
      if (motor[frontRight]==0)
      {
        Left(vexRT[Ch3]);
      }
    }
  if (abs(vexRT[Ch2])<50)
    {
      Right(0);
    }
  if (abs(vexRT[Ch3])<50)
    {
      Left(0);
    }
  }
}
