#pragma config(Motor,  port1,           RotateLeftFront, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port2,           DriveRightFront, tmotorVex393, openLoop)
#pragma config(Motor,  port3,           DriveLeftFront, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           RotateLeftBack, tmotorVex393, openLoop)
#pragma config(Motor,  port5,           RotateRightBack, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           LiftTop,       tmotorVex393, openLoop)
#pragma config(Motor,  port7,           LiftBottom,    tmotorVex393, openLoop)
#pragma config(Motor,  port8,           DriveRightBack, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           DriveLeftBack, tmotorVex393, openLoop)
#pragma config(Motor,  port10,          RotateRightFront, tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
	  if(abs(vexRT[Ch2]) > 50)
	  {
	    if(abs(vexRT[Ch2]) <115)
	    {
	      motor[DriveRightBack] = vexRT[Ch2]/2;
	      motor[DriveRightFront] = vexRT[Ch2]/2;
	    }
	    else
	    {
	      motor[DriveRightBack] = vexRT[Ch2];
	      motor[DriveRightFront] = vexRT[Ch2];
	    }
	   }
	   else
	   {
	      motor[DriveRightBack] = 0;
	      motor[DriveRightFront] = 0;
	   }


	  if(abs(vexRT[Ch3]) > 50)
	  {
	    if(abs(vexRT[Ch3]) <115)
	    {
	      motor[DriveLeftBack] = vexRT[Ch3]/2;
	      motor[DriveLeftFront] = vexRT[Ch3]/2;
	    }
	    else
	    {
	      motor[DriveLeftBack] = vexRT[Ch3];
	      motor[DriveLeftFront] = vexRT[Ch3];
	    }
	   }
	   else
	   {
	      motor[DriveLeftBack] = 0;
	      motor[DriveLeftFront] = 0;
	   }


	  if(vexRT(Btn5D) == 1)
	  {
	    motor[LiftTop] = 127;
	    motor[LiftBottom] = 127;
	  }
	  else if(vexRT(Btn5U) == 1)
	  {
	    motor[LiftTop] = -127;
	    motor[LiftBottom] = -127;
	  }
	  else
	  {
	    motor[LiftTop] = 0;
	    motor[LiftBottom] = 0;
	  }

	  if(vexRT(Btn6D) == 1)
	  {
	    motor[RotateLeftBack] = 127;
	    motor[RotateLeftFront] = 127;
	    motor[RotateRightBack] = 127;
	    motor[RotateRightFront] = 127;
	  }
	  else
	  {
	    if(vexRT(Btn6U) == 1)
	    {
	       motor[RotateLeftBack] = -127;
	    motor[RotateLeftFront] = -127;
	    motor[RotateRightBack] = -127;
	    motor[RotateRightFront] = -127;
	  }
	    else
	  {
	    motor[RotateLeftBack] = 0;
	    motor[RotateLeftFront] = 0;
	    motor[RotateRightBack] = 0;
	    motor[RotateRightFront] = 0;
	  }

	  }

	}
	}
