#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           Frontleft,     tmotorVex393, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port3,           Frontright,    tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port4,           Backright,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           Backleft,      tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int cutOff = 20;
void setMotors(int leftPower, int rightPower){
	if(abs(leftPower) <= cutOff){
		leftPower = 0;
	}
	if(abs(rightPower) <= cutOff){
		rightPower = 0;
	}
	motor[Backleft] = leftPower;
	motor[Backright] = rightPower;
	motor[Frontleft] = leftPower;
	motor[Frontright] = rightPower;
}

void move(int power, int distance){
	setMotors(power, power);
	while(distance >= (abs(nMotorEncoder[Backleft])+ abs(nMotorEncoder[Backright]))/2){
	}
	setMotors(0,0);
	nMotorEncoder[Backleft] = 0;
	nMotorEncoder[Backright] = 0;

}

void SPINNING(int power, int direction, int length){
	setMotors(power*direction, power*-direction);
	while(length>= (abs(nMotorEncoder[Backleft])+ abs(nMotorEncoder[Backright]))/2){
	}
	setMotors(0,0);
	nMotorEncoder[Backleft] = 0;
	nMotorEncoder[Backright] = 0;

}

task main()
{
	while(true){}
//SPINNING(127,-1,10000000);
// INFINITE SPIN LOOP LOL SWAG TROLOLOLOL EVIL DEATH GG YOLO
//move(127,1200);



}
