#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           backLeft,      tmotorVex393, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port3,           backRight,     tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port4,           frontLeft,     tmotorVex393, openLoop)
#pragma config(Motor,  port5,           frontRight,    tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void setMotors(int leftPower, int rightPower){
	motor[backLeft]=leftPower;
	motor[backRight]=rightPower;
	motor[frontLeft]=leftPower;
	motor[frontRight]=rightPower;
}

void waitDistance(int distance){
	while (distance > (abs(nMotorEncoder[backLeft]) + abs(nMotorEncoder[backRight]))/2){}
}
void forward(int distance, int power){
	setMotors(power, power);
	waitDistance(distance);
	setMotors(0, 0);

}
void rotate (int distance, int power, string direction) {
	if(direction = "left"){
		setMotors(-power,power);
	}
	else if(direction = "right"){
		setMotors(power,-power);
	}
}

task main()
{



}
