#pragma config(Sensor, in1,    potent1,             sensorPotentiometer)
#pragma config(Sensor, in2,    potent2,             sensorPotentiometer)
#pragma config(Sensor, in3,    ,                    sensorReflection)
#pragma config(Sensor, in4,    ,                    sensorReflection)
#pragma config(Sensor, in5,    ,                    sensorReflection)
#pragma config(Sensor, dgtl1,  touch,               sensorTouch)
#pragma config(Sensor, dgtl2,  sonar,               sensorSONAR_inch)
#pragma config(Sensor, dgtl4,  encoderRight,        sensorRotation)
#pragma config(Sensor, dgtl5,  encoderLeft,         sensorRotation)
#pragma config(Motor,  port1,           middleFront,   tmotorNormal, openLoop)
#pragma config(Motor,  port2,           frontLeft,     tmotorNormal, openLoop)
#pragma config(Motor,  port3,           frontRight,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port4,           backRight,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port5,           backLeft,      tmotorNormal, openLoop)
#pragma config(Motor,  port6,           liftRight,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port7,           liftLeft,      tmotorNormal, openLoop)
#pragma config(Motor,  port8,           beltRight,     tmotorNormal, openLoop)
#pragma config(Motor,  port9,           beltLeft,      tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port10,          middleBack,    tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main
{
  while(1 == 1)
  {
    if(vexRT[Btn6D] == 1)
    {
      motor[liftRight] = -127;
      motor[liftLeft] = -127;
    }
    else if(vexRT[Btn6U] == 1)
    {
      motor[liftRight] = 127;
      motor[liftLeft] = 127;
    }
    else
    {
      motor[liftRight] = (vexRT[Ch2])/4;
      motor[liftLeft] = (vexRT[Ch3])/4;
    }
  }
}
