#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  encoderLeft,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encoderRight,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  encoderArmLeft, sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  encoderArmRight, sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  touchTop,       sensorTouch)
#pragma config(Sensor, dgtl10, touchBottom,    sensorTouch)
#pragma config(Motor,  port1,           intakeL,       tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port2,           FR,            tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           armLL,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           BL,            tmotorVex393, openLoop)
#pragma config(Motor,  port5,           BR,            tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           armLU,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           armRU,         tmotorVex393, openLoop)
#pragma config(Motor,  port8,           FL,            tmotorVex393, openLoop)
#pragma config(Motor,  port9,           armRL,         tmotorVex393, openLoop)
#pragma config(Motor,  port10,          intakeR,       tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "ChassisFunctions.c"
#include "MiscFunctions.c"
#include "8BarFunctions.c"

task main()
{
	while(true)
	{
		intake(127,127,0);

		if(vexRT[Btn6D] == 1)
		{
			setArm(127, 0);
		}
		else if(vexRT[Btn6U] == 1)
		{
			setArm(-127, 0);
		}
		else
		{
			stopArm();
		}

		if(vexRT[Btn8U] == 1)
		{
			setRightDrive(127, 0);
			setLeftDrive(127, 0);
		}
		else if(vexRT[Btn8D] == 1)
		{
			setRightDrive(-127, 0);
			setLeftDrive(-127, 0);
		}
		else if(vexRT[Btn8R] == 1)
		{
			setRightDrive(-127, 0);
			setLeftDrive(127, 0);
		}
		else if(vexRT[Btn8L] == 1)
		{
			setRightDrive(127, 0);
			setLeftDrive(-127, 0);
		}
		else if(vexRT[Btn7U] == 1)
		{
			setRightDrive(64, 0);
			setLeftDrive(64, 0);
		}
		else if(vexRT[Btn7D] == 1)
		{
			setRightDrive(-64, 0);
			setLeftDrive(-64, 0);
		}
		else if(vexRT[Btn7R] == 1)
		{
			setRightDrive(-64, 0);
			setLeftDrive(64, 0);
		}
		else if(vexRT[Btn7L] == 1)
		{
			setRightDrive(64, 0);
			setLeftDrive(-64, 0);
		}
		else
		{
			stopDrive();
		}
	}
}
