#pragma config(Sensor, in1,    potent1,             sensorPotentiometer)
#pragma config(Sensor, in6,    lineLeft,            sensorLineFollower)
#pragma config(Sensor, in7,    lineMiddle,          sensorLineFollower)
#pragma config(Sensor, in8,    lineRight,           sensorLineFollower)
#pragma config(Sensor, dgtl1,  touch,               sensorTouch)
#pragma config(Sensor, dgtl2,  sonar,               sensorSONAR_inch)
#pragma config(Sensor, dgtl4,  encoderRight,        sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  encoderLeft,         sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  beltTouch,           sensorTouch)
#pragma config(Sensor, dgtl9,  encoderArm,          sensorQuadEncoder)
#pragma config(Motor,  port1,           middleFront,   tmotorNormal, openLoop)
#pragma config(Motor,  port2,           frontLeft,     tmotorNormal, openLoop)
#pragma config(Motor,  port3,           frontRight,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port4,           backRight,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port5,           backLeft,      tmotorNormal, openLoop)
#pragma config(Motor,  port6,           liftRight,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port7,           liftLeft,      tmotorNormal, openLoop)
#pragma config(Motor,  port8,           beltRight,     tmotorNormal, openLoop)
#pragma config(Motor,  port9,           beltLeft,      tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port10,          middleBack,    tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main
{
  int distance = 725;
   while(SensorValue[touch] == 0)
  {
    motor[liftLeft] = -127;
    motor[liftRight] = -127;
  }
  motor[liftLeft] = 0;
    motor[liftRight] = 0;




    motor[liftLeft] = 127;
    motor[liftRight] = 127;
    wait1Msec(4300);
    motor[liftLeft] = 0;
    motor[liftRight] = 0;
    while(SensorValue[beltTouch] == 0)
    {
    }
    SensorValue[encoderLeft] = 0;
    SensorValue[encoderRight] = 0;
    while((SensorValue[encoderLeft] + SensorValue[encoderRight])/2 < distance)
    {
      motor[frontLeft] = 127;
      motor[backLeft] = 127;
      motor[frontRight] = 127;
      motor[backRight] = 127;

    }
    motor[frontLeft] = 0;
      motor[backLeft] = 0;
      motor[frontRight] = 0;
      motor[backRight] = 0;

    motor[beltLeft] = -127;
    motor[beltRight] = -127;
    wait1Msec(3000);
    motor[beltLeft] = 0;
    motor[beltRight] = 0;

    while((SensorValue[encoderLeft] + SensorValue[encoderRight])/2 > 0)
    {
      motor[frontLeft] = -127;
      motor[backLeft] = -127;
      motor[frontRight] = -127;
      motor[backRight] = -127;

    }

    motor[frontLeft] = 0;
      motor[backLeft] = 0;
      motor[frontRight] = 0;
      motor[backRight] = 0;

      while(SensorValue[beltTouch] == 0)
    {
    }
    SensorValue[encoderLeft] = 0;
    SensorValue[encoderRight] = 0;
    while((SensorValue[encoderLeft] + SensorValue[encoderRight])/2 < distance)
    {
      motor[frontLeft] = 127;
      motor[backLeft] = 127;
      motor[frontRight] = 127;
      motor[backRight] = 127;

    }
    motor[frontLeft] = 0;
      motor[backLeft] = 0;
      motor[frontRight] = 0;
      motor[backRight] = 0;

    motor[beltLeft] = -127;
    motor[beltRight] = -127;
    wait1Msec(3000);
    motor[beltLeft] = 0;
    motor[beltRight] = 0;

    while((SensorValue[encoderLeft] + SensorValue[encoderRight])/2 > 0)
    {
      motor[frontLeft] = -127;
      motor[backLeft] = -127;
      motor[frontRight] = -127;
      motor[backRight] = -127;

    }

    motor[frontLeft] = 0;
      motor[backLeft] = 0;
      motor[frontRight] = 0;
      motor[backRight] = 0;


   while(SensorValue[touch] == 0)               //lower arm
  {
    motor[liftLeft] = -127;
    motor[liftRight] = -127;
  }
  motor[liftLeft] = 0;
    motor[liftRight] = 0;

    SensorValue[encoderLeft] = 0;
    SensorValue[encoderRight] = 0;
     while(SensorValue[beltTouch] == 0)
    {
    }


      motor[frontLeft] = 127;
      motor[backLeft] = 127;
      motor[frontRight] = 127;
      motor[backRight] = 127;
      motor[beltLeft] = 127;
    motor[beltRight] = 127;

    wait1Msec(3500);

    motor[beltLeft] = 0;
    motor[beltRight] = 0;
      motor[frontLeft] = -70;
      motor[backLeft] = -70;
      motor[frontRight] = -127;
      motor[backRight] = -127;

    wait1Msec(3500);

    motor[frontLeft] = 0;
      motor[backLeft] = 0;
      motor[frontRight] = 0;
      motor[backRight] = 0;


    motor[liftLeft] = 127;
    motor[liftRight] = 127;
    wait1Msec(4300);
    motor[liftLeft] = 0;
    motor[liftRight] = 0;

    while(SensorValue[beltTouch] == 0)
    {
    }
    SensorValue[encoderLeft] = 0;
    SensorValue[encoderRight] = 0;
    while((SensorValue[encoderLeft] + SensorValue[encoderRight])/2 < distance)
    {
      motor[frontLeft] = 127;
      motor[backLeft] = 127;
      motor[frontRight] = 127;
      motor[backRight] = 127;

    }
    motor[frontLeft] = 0;
      motor[backLeft] = 0;
      motor[frontRight] = 0;
      motor[backRight] = 0;

    motor[beltLeft] = -127;
    motor[beltRight] = -127;
    wait1Msec(3000);
    motor[beltLeft] = 0;
    motor[beltRight] = 0;

    while((SensorValue[encoderLeft] + SensorValue[encoderRight])/2 > 0)
    {
      motor[frontLeft] = -127;
      motor[backLeft] = -127;
      motor[frontRight] = -127;
      motor[backRight] = -127;

    }

    motor[frontLeft] = 0;
      motor[backLeft] = 0;
      motor[frontRight] = 0;
      motor[backRight] = 0;

      while(SensorValue[touch] == 0)               //lower arm
  {
    motor[liftLeft] = -127;
    motor[liftRight] = -127;
  }
  motor[liftLeft] = 0;
    motor[liftRight] = 0;
}
