#pragma config(Sensor, in1,    ArmPotent,           sensorPotentiometer)
#pragma config(Motor,  port1,           frontCenter,   tmotorNormal, openLoop)
#pragma config(Motor,  port2,           frontLeft,     tmotorNormal, openLoop)
#pragma config(Motor,  port3,           frontRight,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port4,           backRight,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port5,           backLeft,      tmotorNormal, openLoop)
#pragma config(Motor,  port6,           backCenter,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port7,           liftRight,     tmotorNormal, openLoop)
#pragma config(Motor,  port8,           liftLeft,      tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port9,           beltRight,     tmotorNormal, openLoop)
#pragma config(Motor,  port10,          beltLeft,      tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main ()
{
  int threshold = 30;
  int slowThreshold = 100;// sets the threshold value
           // sets the top limit

  while(1 == 1)
  {
    if(abs(vexRT[Ch2])>slowThreshold)
    {
      motor[frontRight]  = (vexRT[Ch2]);
      motor[backRight] = (vexRT[Ch2]);
    }
    else if(abs(vexRT[Ch2]) > threshold)                //if the joystick is beyond the threshold move the motor
    {
      motor[frontRight]  = (vexRT[Ch2])/2;
      motor[backRight] = (vexRT[Ch2])/2;
    }
    else
    {
      motor[frontRight]  = 0;
      motor[backRight] = 0;
    }
    if(abs(vexRT[Ch3]) > slowThreshold)
  {
      motor[frontLeft] = (vexRT[Ch3]);
      motor[backLeft] = (vexRT[Ch3]);
    }
    else if(abs(vexRT[Ch3]) > threshold)
  {
      motor[frontLeft] = (vexRT[Ch3])/2;
      motor[backLeft] = (vexRT[Ch3])/2;
    }
    else
    {
    motor[frontRight]  = 0;
      motor[backRight] = 0;
    }

    if(abs(vexRT[Ch2]) > 0 && (vexRT[Ch3]) < 0)
    {
      motor[frontCenter] = (vexRT[Ch2])/6;
      motor[backCenter] = (vexRT[Ch3])/2;
    }


    if(abs(vexRT[Ch2]) < 0 && (vexRT[Ch3]) > 0)
    {
      motor[frontCenter] = (vexRT[Ch3])/6;
      motor[backCenter] = (vexRT[Ch2])/2;
    }

    if(vexRT[Btn5U] == 1)                  //if the top left trigger is pressed set motor to high
    {
      motor[frontCenter] = -127;
      motor[backCenter] = -127;
    }
    else if(vexRT[Btn5U] == 0)
    {
      motor[frontCenter] = 0;
      motor[backCenter] = 0;
    }
    if(vexRT[Btn6U] == 1)
    {
      motor[frontCenter] = 127;
      motor[backCenter] = 127;
    }
    else if(vexRT[Btn6U] == 0)
    {
      motor[frontCenter] = 0;
      motor[backCenter] = 0;
    }

    if(vexRT[Btn5D] == 1)                  //if the top bottom trigger is pressed set motor to low
    {
      motor[frontCenter] = -64;
      motor[backCenter] = -64;
    }
    else if(vexRT[Btn5D] == 0)
    {
      motor[frontCenter] = 0;
      motor[backCenter] = 0;
    }
    if(vexRT[Btn6D] == 1)
    {
      motor[frontCenter] = 64;
      motor[backCenter] = 64;
    }
    else if(vexRT[Btn6D] == 0)
    {
      motor[frontCenter] = 0;
      motor[backCenter] = 0;
    }

    if (abs(vexRT[Ch3Xmtr2]) > threshold)         //if the arm is withing its range
    {
      motor[liftRight] = (vexRT[Ch3Xmtr2]);
      motor[liftLeft] = (vexRT[Ch3Xmtr2]);
    }
    else
    {
      motor[liftRight] = 0;
      motor[liftLeft] = 0;
    }

    if (abs(vexRT[Ch2Xmtr2]) > threshold)
    {
      motor[beltRight] = 127;
      motor[beltLeft] = 127;
    }
    else
  {
      motor[beltRight] = 0;
      motor[beltLeft] = 0;
    }
      }
}
