#pragma config(Sensor, dgtl1,  arm,                 sensorTouch)
#pragma config(Motor,  port1,           frontCenter,   tmotorNormal, openLoop)
#pragma config(Motor,  port2,           frontLeft,     tmotorNormal, openLoop)
#pragma config(Motor,  port3,           frontRight,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port4,           backRight,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port5,           backLeft,      tmotorNormal, openLoop)
#pragma config(Motor,  port6,           backCenter,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port7,           liftRight,     tmotorNormal, openLoop)
#pragma config(Motor,  port8,           liftLeft,      tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port9,           beltRight,     tmotorNormal, openLoop)
#pragma config(Motor,  port10,          beltLeft,      tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
   while(1 == 1)
  {
if(abs(vexRT[Ch2]) <50 )      //This segment acts as a threshold and will not allow motor to run if value is too small
  {
         motor[frontRight] = 0;
         motor[backRight] = 0;
  }
    else
  {
          motor[frontRight] = (vexRT[Ch2]);
          motor[backRight] = (vexRT[Ch2]);
  }


    if(abs(vexRT[Ch3]) <50 )      //This segment acts as a threshold and will not allow motor to run if value is too small
  {
    motor[frontLeft] = 0;
    motor[backLeft] = 0;
  }
  else
  {
    motor[frontLeft] = (vexRT[Ch3]);
    motor[backLeft] = (vexRT[Ch3]);
  }



    if(vexRT[Btn6U] == 1)      //If button 6U is pressed:
  {
       if(SensorValue[arm]==1)
          {

              motor[liftLeft] = 0;
              motor[liftRight] = 0;
          }
        else
          {
              motor[liftLeft] =



              127;
              motor[liftRight] = 127;
          }
  }
  else if(vexRT[Btn6D] == 1) //If button 6D is pressed:
  {
          motor[liftLeft] = -127;
        motor[liftRight] = -127;
  }
  else                       //If neither buttons 6U or 6D are pressed:
  {
     motor[liftLeft] = 0;
     motor[liftRight] = 0;
  }


if(vexRT[Btn5U] == 1)      //If button 5U is pressed:
  {
        motor[beltLeft] = 127;
        motor[beltRight] = 127;
  }
  else if(vexRT[Btn5D] == 1) //If button 5D is pressed:
  {
          motor[beltLeft] = -127;
        motor[beltRight] = -127;
  }
  else                       //If neither buttons 5U or 5D are pressed:
  {
     motor[beltLeft] = 0;
     motor[beltRight] = 0;
  }

if(vexRT[Btn8R] == 1)      //If button 5U is pressed:
  {
        motor[frontCenter] = 127;
        motor[backCenter] = 127;
  }
  else if(vexRT[Btn8L] == 1) //If button 5D is pressed:
  {
          motor[frontCenter] = -127;
        motor[backCenter] = -127;
  }
  else                       //If neither buttons 5U or 5D are pressed:
  {
     motor[frontCenter] = 0;
     motor[backCenter] = 0;
  }
}

}
