#pragma config(Sensor, in1,    potent1,             sensorPotentiometer)
#pragma config(Sensor, in6,    lineLeft,            sensorLineFollower)
#pragma config(Sensor, in7,    lineMiddle,          sensorLineFollower)
#pragma config(Sensor, in8,    lineRight,           sensorLineFollower)
#pragma config(Sensor, dgtl1,  touch,               sensorTouch)
#pragma config(Sensor, dgtl2,  sonar,               sensorSONAR_inch)
#pragma config(Sensor, dgtl4,  encoderRight,        sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  encoderLeft,         sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  beltTouch,           sensorTouch)
#pragma config(Sensor, dgtl9,  encoderArm,          sensorQuadEncoder)
#pragma config(Motor,  port1,           middleFront,   tmotorNormal, openLoop)
#pragma config(Motor,  port2,           frontLeft,     tmotorNormal, openLoop)
#pragma config(Motor,  port3,           frontRight,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port4,           backRight,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port5,           backLeft,      tmotorNormal, openLoop)
#pragma config(Motor,  port6,           liftRight,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port7,           liftLeft,      tmotorNormal, openLoop)
#pragma config(Motor,  port8,           beltRight,     tmotorNormal, openLoop)
#pragma config(Motor,  port9,           beltLeft,      tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port10,          middleBack,    tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main
{
  int multiplier = 2;
  int distance = 725;
  while((SensorValue[encoderLeft] + SensorValue[encoderRight])/2 < distance)      //drive to goal
    {
      if(SensorValue[encoderLeft]>SensorValue[encoderRight])
      {
        motor[frontLeft] = 127-(multiplier * (SensorValue[encoderLeft] - SensorValue[encoderRight]));
        motor[backLeft] = 127-(multiplier * (SensorValue[encoderLeft] - SensorValue[encoderRight]));
      }
      else if(SensorValue[encoderLeft]<SensorValue[encoderRight])
      {
        motor[backRight] = 127-(multiplier * (SensorValue[encoderRight] - SensorValue[encoderLeft]));
        motor[frontRight] = 127-(multiplier * (SensorValue[encoderRight] - SensorValue[encoderLeft]));
      }
      else
      {
        motor[frontLeft] = 127;
        motor[backLeft] = 127;
        motor[frontRight] = 127;
        motor[backRight] = 127;
      }

    }

     while((SensorValue[encoderLeft] + SensorValue[encoderRight])/2 > 0)           //go back
    {
      if(SensorValue[encoderLeft]<SensorValue[encoderRight])
      {
        motor[frontLeft] = -127+(multiplier * (SensorValue[encoderLeft] - SensorValue[encoderRight]));
        motor[backLeft] = -127+(multiplier * (SensorValue[encoderLeft] - SensorValue[encoderRight]));
      }
      else if(SensorValue[encoderLeft]>SensorValue[encoderRight])
      {
        motor[backRight] = -127+(multiplier * (SensorValue[encoderRight] - SensorValue[encoderLeft]));
        motor[frontRight] = -127+(multiplier * (SensorValue[encoderRight] - SensorValue[encoderLeft]));
      }
      else
      {
        motor[frontLeft] = -127;
        motor[backLeft] = -127;
        motor[frontRight] = -127;
        motor[backRight] = -127;
      }
    }
}
