#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  encoderLeft,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encoderRight,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  encoderArmLeft, sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  encoderArmRight, sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  touchTop,       sensorTouch)
#pragma config(Sensor, dgtl10, touchBottom,    sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           intakeL,       tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port2,           FR,            tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port3,           armLL,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           BL,            tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port5,           BR,            tmotorVex393HighSpeed, openLoop, reversed, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port6,           armLU,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           armRU,         tmotorVex393, openLoop)
#pragma config(Motor,  port8,           FL,            tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port9,           armRL,         tmotorVex393, openLoop)
#pragma config(Motor,  port10,          intakeR,       tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//!!!!!!!! status port on power expander goes analog2(in8) on the cortex!!!!!!!!!!//
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "8BarFunctions.c"
#include "ChassisFunctions.c"
#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

//cutOff = a motor power beneath which no power will be sent to the motor
int driveCutOff = 30;
int armCutOff = 0;
int intakeCutOff = 0;

int forwardPower = 127;
int intakePower = -127;
int armPower = 127;


const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;

//Wait for Press--------------------------------------------------
void waitForPress()
{
	while(nLCDButtons == 0){}
	wait1Msec(5);
}
//----------------------------------------------------------------

//Wait for Release------------------------------------------------
void waitForRelease()
{
	while(nLCDButtons != 0){}
	wait1Msec(5);
}

task autonomous()
{
	int driveSpeed = 127;
	int intakeSpeed = -127;
	int intakeTime = 3000;
	int troughTime = 2000;
	int bonusTime = 1950;
	lowerArm();

	//go dump preloads
	while(SensorValue[encoderArmLeft] <75)
	{
		setArm(127, 0);
	}

	stopArm();
	waitForPress();
	setDrive(driveSpeed, 0);
	wait1Msec(troughTime);
	stopDrive();
	startIntake(-1*intakeSpeed, 0);
	wait1Msec(intakeTime);
	stopIntake();
	setDrive(-1*driveSpeed, 0);
	wait1Msec(troughTime);
	stopDrive();
	lowerArm();

	//get bonus
	waitForPress();
	setDrive(driveSpeed, 0);
	startIntake(intakeSpeed, 0);
	wait1Msec(bonusTime);
	stopDrive();
	wait1Msec(intakeTime);
	stopIntake();
	setDrive(-1*driveSpeed, 0);
	wait1Msec(bonusTime);
	stopDrive();
	while(SensorValue[encoderArmLeft] <75)
	{
		setArm(127, 0);
	}
	stopArm();

	//go dump bonus
	waitForPress();
	setDrive(driveSpeed, 0);
	wait1Msec(troughTime);
	stopDrive();
	startIntake(-1*intakeSpeed, 0);
	wait1Msec(intakeTime);
	stopIntake();
	setDrive(-1*driveSpeed, 0);
	wait1Msec(troughTime);
	stopDrive();
	lowerArm();
}




/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

//////////////////mechanum drive//////////////////////////////////////
//bottomThresh = a value beneath which a channel will not have any input
int bottomThresh = 0;
//topThresh = a value beneath which a channel will input a fraction of its value
int topThresh = 0;
//lowGear = a value by which a channel will be divided when below topThresh
int lowGear = 0;

//////////////////////////arm/////////////////////////////////
//trough = the height of the trough as specified by the encoders
int trough = 75;
//highGoal = the height of the trough as specified by the encoders
int highGoal = 0;
//armSpeed = the base value for the arm
int armSpeed = 127;

//////////////////////////intake//////////////////////////////
//inSpeed = speed of intaking
int inSpeed = 127;
//outSpeed = speed of depositing
int outSpeed = 127;


task usercontrol()
{
	// User control code here, inside the loop

	while(true)
	{
		//runs the joystick control of the chassis
		MechanumDrive(bottomThresh, topThresh, lowGear, driveCutOff);

		//runs arm control with presets and arm adjust on the LCD buttons
		armControl(trough, highGoal, armSpeed, armCutOff);

		//runs intake with control
		intake(inSpeed, outSpeed, intakeCutOff);

		//if the center button is pressed
		if(nLCDButtons == 2)
		{
			if(!batteryView)
			{
				//StartTask(battery, 2);
				batteryView = true;
			}
		}

		//universal framerate for PID
		wait1Msec(50);
	}
}
