#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  encoderLeft,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encoderRight,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  encoderArmLeft, sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  encoderArmRight, sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  touchTop,       sensorTouch)
#pragma config(Sensor, dgtl10, touchBottom,    sensorTouch)
#pragma config(Motor,  port1,           intakeL,       tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port2,           FR,            tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           armLL,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           BL,            tmotorVex393, openLoop)
#pragma config(Motor,  port5,           BR,            tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           armLU,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           armRU,         tmotorVex393, openLoop)
#pragma config(Motor,  port8,           FL,            tmotorVex393, openLoop)
#pragma config(Motor,  port9,           armRL,         tmotorVex393, openLoop)
#pragma config(Motor,  port10,          intakeR,       tmotorVex393, openLoop)
#pragma config(UART_Usage, UART2, uartVEXLCD, baudRate19200, IOPins, None, None)
//!!!!!!!! status port on power expander goes analog2(in8) on the cortex!!!!!!!!!!//
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "ChassisFunctions.c"
#include "8BarFunctions.c"

//////////////////mechanum drive//////////////////////////////////////
//bottomThresh = a value beneath which a channel will not have any input
int bottomThresh = 0;
//topThresh = a value beneath which a channel will input a fraction of its value
int topThresh = 0;
//lowGear = a value by which a channel will be divided when below topThresh
int lowGear = 0;

//////////////////////////arm/////////////////////////////////
//trough = the height of the trough as specified by the encoders
int trough = 0;
//highGoal = the height of the trough as specified by the encoders
int highGoal = 0;
//armSpeed = the base value for the arm
int armSpeed = 127;

//////////////////////////intake//////////////////////////////
//inSpeed = speed of intaking
int inSpeed = 127;
//outSpeed = speed of depositing
int outSpeed = 127;

//////////////////////////general/////////////////////////////
//cutOff = a motor power beneath which no power will be sent to the motor
int driveCutOff = 30;
int armCutOff = 0;
int intakeCutOff = 0;

task main()
{
	while(true)
	{
		//runs the joystick control of the chassis
		MechanumDrive(bottomThresh, topThresh, lowGear, driveCutOff);

		//runs arm control with presets and arm adjust on the LCD buttons
		armControl(trough, highGoal, armSpeed, armCutOff);

		//runs intake with control
		intake(inSpeed, outSpeed, intakeCutOff);

		//if the center button is pressed
		if(nLCDButtons == 2)
		{
			if(!batteryView)
			{
				//StartTask(battery, 2);
				batteryView = true;
			}
		}

		//universal framerate for PID
		wait1Msec(50);
	}
}
